#!/usr/bin/env bash
source /dev/stdin < <(cli loader)
source /dev/stdin < <(integrate area .group)

help() {
    cat << EOF
Command
    integrate area circle

Arguments
    --radius     [Required] : Radius of the circle.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::multiply ${CONSTANT_PI} $(integrate::area::square ${arg_radius}))
}

cli::load "$@"