#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_PATH}

Arguments
    --radius     [Required] : Radius of the circle.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::multiply ${CONSTANT_PI} $(math::square ${arg_radius}))
}

cli::load "$@"