#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Arguments
    --side        [Required] : Length of a side.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::square ${arg_side})
}

self_test() {
    source /dev/stdin < <(cli::import cli_assert)
    assert::eq $(${CLI_COMMAND} --side 10) 100
}

cli::load "$@"