#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    integrate volume cube

Arguments
    --side       [Required] : Length of a side.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::cube ${arg_side})
}

cli::load "$@"