#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Arguments
    --radius     [Required] : Radius of the circle.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::multiply '0.75' ${CONSTANT_PI} \
        $(math::cube ${arg_radius}))
}

cli::main "$@"