#!/usr/bin/env bash
source /dev/stdin < <(cli loader)
cli::import integrate volume .group

help() {
    cat << EOF
Command
    integrate area circle

Arguments
    --radius     [Required] : Radius of the circle.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

main() {
    echo $(math::multiply '0.75' ${CONSTANT_PI} \
        $(math::cube ${arg_radius}))
}

cli::load "$@"